app-url: http://localhost/
db:
  host: localhost
  port: 3306
  database: db
  username: root
  password: root
redis:
  host: localhost
  port: 6379
  db: 1
  password:
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  queues:
    process: gofiber-web-template-process